name: Continuous Integration

on:
  pull_request:
  
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          flutter pub get
          dart analyze
#          flutter test